### ISSUE TITLE
exercise-regexp

### ISSUE THREAD

**Issue by crguezl** [sokartema/gitbook-plugin-jazer#1]
@sokartema, veo  que ya miraste [GitbookIO/plugin](https://github.com/GitbookIO/plugin).

Echale un vistazo también al fuente de  [marcjansen/plugin-exercises](https://github.com/marcjansen/plugin-exercises). Puede que sea un poco complicado pero  creo que se puede aprender un poco de como está escrito.

Mi idea inicial era partir del código  [marcjansen/plugin-exercises](https://github.com/marcjansen/plugin-exercises) que está escrito para comprobar que JS arbitrario escrito por el _lector_ cumple el `assert` escrito por el _autor_ y  cambiarlo/**simplificarlo** para crear un `gitbook-plugin-regexp-exercises`  en el que  el _autor_ escribe una `regexp` y el `assert` sería que lo escrito por el _lector_ casa con la `regexp` escrita por el autor. Algo así:

``` javascript
{% exercise-regexp %}
¿Capital de Italia?
{% solution %}
Roma
{% validation %}
/\s*Roma\s*/i
{% endexercise-regexp %}
```

**Comment by sokartema** [comment]
Ya hay una version inicial disponible de lo que comentabas. Cierro este issue. Un saludo!

**Comment by crguezl** [comment]
¡Bravo!
