### ISSUE TITLE
edición de la entrada

### ISSUE THREAD

**Issue by crguezl** [sokartema/gitbook-plugin-jazer#11]
Usar el editor `ace` para mejorar la edición de la entrada

**Comment by sokartema** [comment]
Estaba pensando que ya que no queremos introducir texto tipo codigo como ace, seria mejor barajar otra opcion como quill http://quilljs.com/examples/

**Comment by crguezl** [comment]
Uhmmm....

No estoy seguro. 

[quilljs](http://quilljs.com/) me parece espartano. 

[ace](https://ace.c9.io/) **puede ser usado para todo** y lo usa c9.

Sospecho que los usuarios de tu plugin serán gente como yo, del mundo de la programación (cualquiera no se atreve a escribir  una regexp) y que muchas de las preguntas que se escriban serán relacionadas con la programación.

**Comment by sokartema** [comment]
Ya se está usando ace y lo cambié por el input actual.

**Comment by crguezl** [comment]
Quítale los números de línea por defecto (luego lo podrá configurar el autor):

``` javascript
editor.renderer.setShowGutter(false);
```
