### ISSUE TITLE
plugin questionjs

### ISSUE THREAD

**Issue by crguezl** [sokartema/gitbook-plugin-jazer#14]
Un par de ejemplos de como me imagino un borrador de lo que sería el plugin con validación de la respuesta en JavaScript:

``` javascript
{% questionjs %}
¿Quienes reinaban en España cuando se descubrió America?
{% solution %}
Los Reyes Católicos
{% validation %}
function(respuesta) {
  if (respuesta.match(/reyes\s+catolicos/i)) return true;
  if (respuesta.match(/isabel/i && respuesta.match(/fernando/i) ) return true;
  return false;
}
{% endquestionjs %}
```

``` javascript
{% questionjs %}
Escriba un número primo mayor que 20
{% solution %}
Son soluciones 23, 31, 37 ...
{% validation %}
function(respuesta) {
  var x = parseInt(respuesta);
  if (x !== respuesta) return false; // no es entero
  if (x <=20) return false;               // no es mayor que 20
  for(var i=2; i<= x/2; i++) {
    if (x%i == 0) return false;
  }
  return true;   
}
{% endquestionjs %}
```
- Posiblemente sería bueno que el autor -si lo desea - pudiera cargar librerías de apoyo usando [requirejs](http://requirejs.org/) o algo por el estilo
- De hecho la función podría hacer un request AJAX a un servidor y obtener la respuesta desde el mismo
- Puede que fuera interesante que la función reciba además del primer parámetro `respuesta`un segundo parámetro con el objeto `book` representando al libro de tal manera que se tuviera todo el contexto necesario para elaborar una respuesta adecuada

Otro ejemplo con `support`:

``` javascript
{% questionjs %}
Escriba un número primo mayor que 20
{% solution %}
Son soluciones 23, 31, 37 ...
{% validation %}
function(respuesta) {
  var x = parseInt(respuesta);
  if (eq(x, respuesta)) return false; // no es entero
  if (x <=20) return false;               // no es mayor que 20
  for(var i=2; i<= x/2; i++) {
    if (x%i == 0) return false;
  }
  return true;   
}
{% support %}
function eq(x, y) {
  return x == y;
}
{% endquestionjs %}
```

**Comment by crguezl** [comment]
Considerar la posibilidad de poner en la configuración del plugin una opción para de cargar librerías javascript

**Comment by sokartema** [comment]
Estoy con esto ahora, la parte de configuracion desde el book.json ya la he logrado realizar.

**Comment by sokartema** [comment]
@crguezl Por ahora se pueden incluir cdn's en el book.json de la siguiente manera: 

```
  "pluginsConfig":{
      "jazer": {
          "width": "80%",
          "height": "20%",
          "color": "#BB504B",
          "gutter": "false",
          "support": ["https://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.min.js","https://ajax.googleapis.com/ajax/libs/mootools/1.6.0/mootools.min.js"]
      }
  }
```

Para la version 1.0.46 voy a pulirlo un poco mas.
