### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by crguezl** [sokartema/gitbook-plugin-jazer#17]
Puesto que ya estamos en versión casi beta, sería conveniente que añadieras un fichero `LICENSE` al proyecto. Elige el que creas mejor.

La gente de gitbook ha optado por la de [Apache  Version 2.0, January 2004](https://github.com/GitbookIO/gitbook/blob/master/LICENSE).

[Esto es lo que visto que la ULL recomienda al respecto](http://osl.ull.es/licencias/recomendaci%C3%B3n-de-la-fsf-sobre-la-elecci%C3%B3n-de-licencia/) no sé si habrá algo mas.

**Comment by sokartema** [comment]
Quizás deberiamos adoptar tambien la licencia apache que comentastes, ya que segun dice el enlace de la ULL la GPL se utiliza para proyectos mas grandes.

**Comment by crguezl** [comment]
De acuerdo 👍
