### ISSUE TITLE
regexp y jsquestion con array de respuestas

### ISSUE THREAD

**Issue by crguezl** [sokartema/gitbook-plugin-jazer#18]
Estoy escribiendo un examen en gitbook y he visto que el planteamiento inicial de las preguntas `regexp` y  `questionjs`  no sirve  para ejercicios en los que lo que se necesita es que el alumno rellene diversas partes de un texto que se le deja incompleto.

Por ejemplo:

_1.  Complete las partes que faltan del siguiente `gulpfile.js` en el que
    se lleva a cabo una tarea para la optimización (uglify/minify) de la
    aplicación vista en clase de la práctica de la temperatura:_

``` javascript
var gulp    = require('gulp'),
    gutil   = require('gulp-util'),
    uglify  = require('gulp-uglify'),
    concat  = require('gulp-concat');
var minifyHTML = require('gulp-minify-html');
var minifyCSS  = require('gulp-minify-css');

gulp.____('minify', function () {
  gulp.___('temperature.js')
  .____(uglify())
  .___(gulp.____('minified'));

  gulp.__('./index.html')
    .___(minifyHTML())
    .___(gulp.___('./minified/'))

  gulp.__('./*.css')
   .___(minifyCSS({keepBreaks:true}))
   .___(gulp.___('./minified/'))
});
```
- En estos casos lo que recibe el código de validación es un `array`de cadenas y no una sóla cadena.
- En este caso los inputs se distribuyen alrededor del texto de descripción del problema
- Quizá los tamaños (`width`) de los elementos `<input>`  deberían ser proporcionales al número de sub-guiones utilizados.
- No sé si estamos hablando de un nuevo tipo de problema o de que los tipos `regexp` y `jsexercise` deberían ser más flexibles y generales
- Si además como en este caso son muchos los huecos puede ser una auténtica lata llevar la cuenta del orden de los huecos. Posiblemente sería mejor una especificación en la que la `regexp`de validación (función de validación) sigue a la cadena de subguiones:

``` javascript
gulp.__{% /src/ %}('./*.css')
   .___{% /pipe/ %}(minifyCSS({keepBreaks:true}))
   .___{% /pipe %}(gulp.___{% /dest/ %}('./minified/'))
```
- No tengo claro cuán difícil pueda resultar y si valdrá la pena el esfuerzo

**Comment by sokartema** [comment]
No entiendo muy bien el problema, estaria bien verlo en persona y me lo explicases.
