### ISSUE TITLE
añadir texto en la entrada del area de texto de extrada

### ISSUE THREAD

**Issue by crguezl** [sokartema/gitbook-plugin-jazer#19]
## Que pasa?

Se observan varias conductas anómalas o bugs en este [ejemplo](https://gist.githubusercontent.com/crguezl/cafeb39eafd8b7e18a2507400cb51590/raw/20c18fa60c51f68be3675eb437b274b32871813d/README.md). 
- El markdown no parece funcionar en la parte del enunciado.
- Quiero hacer la ventana de entrada del editor mas grande y no lo consigo
- Creo que la regexp debería funcionar sobre la solución y está fracasando!. 
  - Parece que cuando hago `click` en el botón `solution` y después en `submit` me da `fallo` y es porque la solución está TRUNCADA!!!

**Comment by sokartema** [comment]
Falta el codigo del ejemplo creo. 

Podria poner un parametro mas para cambiar el tamaño del editor. 

La validacion de la solucion viene definida por el campo validation no?

El campo solution simplemente es para poner en el editor cual es la posible solucion al ejercicio tras el usuario presionar el boton de solution. 

Un saludo.

**Comment by crguezl** [comment]
Si, perdón. Para descargar el ejemplo:

``` bash
git clone git@gist.github.com:cafeb39eafd8b7e18a2507400cb51590.git
```

**Comment by sokartema** [comment]
Ya esta solucionado creo, miralo y me comentas.
