### ISSUE TITLE
Opciones en regexp

### ISSUE THREAD

**Issue by crguezl** [sokartema/gitbook-plugin-jazer#2]
Sería estupendo poder especificar las opciones de la `RegExp` como `i` (ignore case). Propongo un cambio en la sintáxis. Poner la regexp entre slashes seguida de las opciones como sigue:

```
{% regexp %}
¿Quien descubrió america?
{% solution %}
Cristobal Colon
{% validation %}
/\s*(Cristobal)?\s+Colon\s*/i
{% endregexp %}
```

**Comment by sokartema** [comment]
Ya se permite el uso de las diferentes opciones como la siguiente /\s_(Cristobal)?\s+Colon\s_/i
