### ISSUE TITLE
Tamaños en la ventana del editor 

### ISSUE THREAD

**Issue by crguezl** [sokartema/gitbook-plugin-jazer#20]
- ¿Existe un parámetro `editorWidth`?
- ¿No debería por defecto ocurrir que la ventana del editor fuera igual en altura al tamaño del texto introducido en la sección
  `{% editor %}`?
- Resulta engorroso tener que ir probando alturas en pixels para la ventana del editor hasta dar con la adecuada
- ¿Es posible controlar el font que sale en la zona del editor? 
- El font en el editor sale demasiado grande en este [ejercicio](https://casianorodriguezleon.gitbooks.io/pl1516/content/apuntes/pegjs/ejercicios.html#ejercicio-llamadas-a-función-en-pl01). ¿Hay alguna forma de controlar el tamaño del font en el editor? (¿Quizá se pueda usar algo general de gitbook?¿Tiene gitbook una forma de añadir estilos para secciones?)
- ¿Podría no salir "regexp" en el título de la pregunta? Ese título le da una idea al alumno de como se controla la respuesta y le puede sugerir como hacer un hacking!

**Comment by sokartema** [comment]
> ¿Existe un parámetro editorWidth?

El editorwidth no está definido, simplemente coge el ancho maximo especificado de la ventana del ejercicio, porque si dejaba cambiar el ancho del editor por el usuario podian surgir bugs, como que se saliese del recuadro.

> ¿No debería por defecto ocurrir que la ventana del editor fuera igual en altura al tamaño del texto introducido en la sección {% editor %}?

Podria poner otro parametro para que la altura se ajuste a lo especificado en el block editor y no en el solution, o que por defecto siempre sea el editor a no ser que se especifique otra cosa.

> ¿Es posible controlar el font que sale en la zona del editor? 

Pondre otro parametro para cambiar el tamaño de la fuente en el editor.

> ¿Podría no salir "regexp" en el título de la pregunta? Ese título le da una idea al alumno de como se controla la respuesta y le puede sugerir como hacer un hacking!

Podria poner un parametro para ocultar los titulos y que ponga siempre exercise o que todos los titulos por defecto ya sean Exercise y no se especifique de que es.

Un saludo!

**Comment by sokartema** [comment]
@crguezl Ya esta subida la ultima version:
- `editorAutoHeight` ahora tiene dos opciones "solution" o "editor" y permite calcular el tamaño del editor basado en el bloque solution o en el bloque editor.
- Ahora todos los nombres por defecto de los ejercicios son Exercise.
- Hay un nuevo parametro llamado fontSize y permite cambiar el tamaño de la letra en el editor, admite o "20px" o "20" será calculado en pixeles por igual. Por ahora solo admite esa medida.
- `editorAutoHeight` calcula automaticamente el tamaño del editor teniendo en cuenta el tamaño actual de la fuente.

Un saludo.

**Comment by crguezl** [comment]
Genial
