### ISSUE TITLE
Estilo

### ISSUE THREAD

**Issue by crguezl** [sokartema/gitbook-plugin-jazer#3]
Debería ser posible para el autor del ejercicio definir el ancho del elemento input, el ancho de la ventana, el tamaño de los botones, etc. No es lo mismo que la respuesta sea muy corta que muy larga.

Habrá que considerar dos parametrizaciones. 
- Una en `book.json`  en el atributo `pluginsConfig` del tipo:

```
  "pluginsConfig": {
        "asciitree": {
            "leadingChar": "no need, because plugin will guess leadingChar."
        },
        "jsfiddle": {
            "type": "script",
            "tabs": [
                "result",
                "js",
                "html"
            ],
            "height": "1000",
            "width": "500",
            "fontColor": "00FF00"
        },
        "disqus": {
            "shortName": "gitbookexample"
        }
    }
```
- Y la otra pasándole parámetros a cada sección  `{% regexp %}`

**Comment by sokartema** [comment]
He estado bastante trabado con el tema de la configuracion en el book.json, por lo que he podido ver del plugin autocover, el objeto se obtiene de la siguiente manera:

```
    "finish:before": function() {
            var that = this;
            var pluginConfig = that.config.get('pluginsConfig.jazer', {});

            console.log(pluginConfig);

        }
```

Pero dentro de la sección "Hooks", desde los bloques no se puede acceder a ella, por lo que sigo investigando.

**Comment by sokartema** [comment]
Hay un problema bastante curioso que puede ser un bug de gitbook, mañana hablamos de ello, pero es el siguiente...

Al crear un bloque con argumentos como el siguiente:

```
{% regexp width="40%", height="100px" %}
¿Quien descubrió america?
{% solution %}
Cristobal Colon
{% validation %}
/\s*(Cristobal)?\s+Colon\s*/i
{% endregexp %}

```

Los argumentos que recoge el objeto blk en la funcion del bloque se llama 4 veces, 2 veces por bloque definido, el problema viene en que la primera vez el bloque recoge los argumentos, pero la segunda vez no. Por lo que al pasarle los argumentos al template html, no acaban bien definidos..

```

{ width: '40%', height: '100px', __keywords: true }
{ body: '\n¿Quien descubrió america?\n',
  args: [],
  kwargs: { width: '40%', height: '100px', __keywords: true
  blocks:
   [ { name: 'solution', body: '\nCristobal Colon\n' },
     { name: 'validation',
       body: '\n/\\s*(Cristobal)?\\s+Colon\\s*/i\n' } ] }
{}
{ body: '\n¿4+4?\n',
  args: [],
  kwargs: {},
  blocks:
   [ { name: 'solution', body: '\n8\n' },
     { name: 'validation', body: '\n/\\s*8\\s*/i\n' } ] }
info: start generation with website generator
info: clean website generator
info: OK
{ width: NaN, height: undefined, __keywords: true }
{ body: '\n¿Quien descubrió america?\n',
  args: [],
  kwargs: { width: NaN, height: undefined, __keywords: true
  blocks:
   [ { name: 'solution', body: '\nCristobal Colon\n' },
     { name: 'validation',
       body: '\n/\\s*(Cristobal)?\\s+Colon\\s*/i\n' } ] }
{}
{ body: '\n¿4+4?\n',
  args: [],
  kwargs: {},
  blocks:
   [ { name: 'solution', body: '\n8\n' },
     { name: 'validation', body: '\n/\\s*8\\s*/i\n' } ] }

```

Mañana lo explico mejor... pero se puede observar que los argumentos en los ultimos bloques son NAN y undefined.

**Comment by crguezl** [comment]
Vale la pena mirar como lo hace el plugin [gitbook-plugin-mermaid](https://github.com/JozoVilcek/gitbook-plugin-mermaid)
admite una opción:

_To load graph  put in your book block as:_

```
{% mermaid src="./diagram.mermaid" %}
{% endmermaid %}
```

que es tratado en  su fichero [`index.js`](https://github.com/JozoVilcek/gitbook-plugin-mermaid/blob/master/index.js#L14-L27):

``` javascript
  blocks: {
    mermaid: {
      process: function(block) {
        var body = block.body;

        var src = block.kwargs.src;
        if(src) {
          var relativeSrcPath = url.resolve(this.ctx.file.path, src)
          var absoluteSrcPath = decodeURI(path.resolve(this.book.root, relativeSrcPath))
          body = readFileSync(absoluteSrcPath, 'utf8')
        }

        return processBlock(body);
      }
    }
  }
```

Un issue relacionado con los argumentos de bloque se encuentra en
[este issue de gitbook](https://github.com/GitbookIO/gitbook/issues/934)
`Bad handling of block arguments #934`

**Comment by sokartema** [comment]
En la version 1.0.42 ya está disponible poner los mismos parametros de cada bloque en el archivo book.json de forma general.

```
{

  "plugins": ["jazer","katex"],

  "pluginsConfig":{
      "jazer": {
          "width": "80%",
          "height": "20%",
          "color": "#BB504B",
          "gutter": "false"
      }
  }

}
```
