### ISSUE TITLE
xregexp

### ISSUE THREAD

**Issue by crguezl** [sokartema/gitbook-plugin-jazer#4]
Sería estupendo si se pudieran usar expresiones regulares extendidas via la librería [xregexp](http://xregexp.com/)

**Comment by sokartema** [comment]
Se está utilizando la libreria xregexp para la validación de las expresiones regulares, nose si hace falta que pueda procesar otro tipo de opciones o algo diferente a lo actual.

**Comment by crguezl** [comment]
Si. 

Una  opción que tiene `XRegExp` que es interesante es la opción `x` ya que hace que los blancos dentro de la `XRegExp` no sean significativos y que puedan ponerse comentarios dentro de la expresión regular (`# ...`). 

Un ejemplo de uso:

```
{% regexp %}
¿Quienes reinaban en España cuando se descubrió America?
{% solution %}
Los Reyes Católicos
{% validation %}
/(Isabel\s+((I\s+)?de\s+Castilla)?+y\s+Fernando(\s+(II\s+)?de\s+Arag[oó]n) # por nombre y título
 |                                                                             
(Reyes\s+Cat[oó]licos)  # conocidos también por este nombre
/ix
{% endregexp %}
```

**Comment by crguezl** [comment]
Tomado de la documentación de `XRegExp`:

_Adds new regex flags:_
- `s`, to make dot (`.`)  [match all characters](http://xregexp.com/flags/#singleline);
- `x`, for free-spacing and line comments; 
- `n`, for [explicit capture](http://xregexp.com/flags/#explicitCapture) mode; and 
- `A`, for [astral mode](http://xregexp.com/flags/#astral) (full 21-bit Unicode matching).

Si el que escribe el ejercicio las pone habría que respetarlas. 
La opción `A` Requires the [Unicode Base addon](http://xregexp.com/plugins/#unicode).

**Comment by crguezl** [comment]
Me equivoqué en decir que 

"_En el caso de la opción `x`habría que además procesar la entrada eliminando todos los retornos de carro y dejando toda la entrada en una sola línea_"

Ya lo hace el constructor de `XRegExp`. No hay que hacerlo.

**Comment by sokartema** [comment]
Aparte de todo esto, ¿las librerias de javascript que se utilizan seria conveniente ponerlas bajo un gestor como bower?

**Comment by crguezl** [comment]
On 19 March 2016 at 01:59, Jazer Abreu Chinea notifications@github.com
wrote:

> Aparte de todo esto, ¿las librerias de javascript que se utilizan seria
> conveniente ponerlas bajo un gestor como bower?

Por ahora las dependencias no son muy complicadas y npm es suficiente pero
 puede que sea una buena idea de cara al futuro

Ya me dices que decides
