### ISSUE TITLE
Generación de pdf, epub y mobi

### ISSUE THREAD

**Issue by crguezl** [sokartema/gitbook-plugin-jazer#7]
Cuando se genera un pdf el ejercicio desaparece. ¿Es eso lo que queremos? ¿O queremos que salga el enunciado de la pregunta con algún formato?

**Comment by sokartema** [comment]
Creo que en este caso deberiamos mostrar la pregunta, pero sin ningun tipo de boton ni editor. O simplemente el input con la respuesta ya introducida.

**Comment by crguezl** [comment]
OK

**Comment by sokartema** [comment]
Esto ya está realizado, me gustaria incluir opciones diferentes para modificar la salida del pdf, como poder ocultar las soluciones, pero eso va en el otro apartado que es bastante complicado.

**Comment by crguezl** [comment]
Estoy de acuerdo en incluir opciones diferentes para modificar la salida a pdf. 

Un posible borrador  de solución  para el pdf y el ebook - pero me parece algo complicada de implantar y tiene algunos inconvenientes - sería:
- Que el autor opcionalmente nos de una etiqueta o bien generar un número para cada pregunta que aparecería junto a la pregunta en itálicas o algún formato especial 
  
  **1.2:** _¿Capital de Italia?_
- Una(s) "hoja(s) de soluciones" (supongo que sería como generar un fichero markdown auxiliar `hojadesolucionesregexp.md` que se colocaría donde el autor quiera) en la que aparecen las soluciones a las preguntas 
- En cada pregunta se pondría un enlace  a su solución, algo como esto: 
  
  ```
  **1.2:** *¿Capital de Italia?*
  <a href="hojadesolucionesregexp.md#275">Solución</a>
  ```
  
  de manera que se pudiera acceder en el pdf
